language: php

sudo: true

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - sqlite

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit --verbose