language: php

sudo: true

php:
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

services:
  - sqlite

before_script:
  - composer install
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - composer show laravel/framework

script:
  - vendor/bin/phpunit